Website/Controllers/Mvc/ExercisesController.cs
using Microsoft.WindowsAzure.Storage.Table;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Runnymede.Common.Models;
using Runnymede.Common.Utils;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Runnymede.Website.Controllers.Mvc
{
    [Authorize]
    public class ExercisesController : Runnymede.Website.Utils.CustomController
    {
        // GET: /exercises/
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        // GET: /exercises/record-speech
        [AllowAnonymous]
        public ActionResult RecordSpeech()
        {
            return View();
        }

        // GET: /exercises/photograph-writing
        [AllowAnonymous]
        public ActionResult PhotographWriting()
        {
            return View();
        }

        // GET: /view/2000000001 by ExerciseId
        [ActionName("View")] // Be carefull, the term "View" has a special meaning in ASP.NET MVC. There is the method View() in the base Controller class.
        public async Task<ActionResult> ViewExercise(int id)
        {
            var exercises = await ExerciseUtils.GetExerciseWithReviews("dbo.exeGetExerciseWithReviews", new { UserId = this.GetUserId(), Id = id, });

            // We got a few rows of the same Exercise, joined with different Reviews. Group them into a single Exercise.               
            var reviews = exercises
                .SelectMany(i => i.Reviews)
                .Where(i => i is ReviewDto) // Otherwise an absent review is deserialized by Dapper as null. i.e [null].
                .OrderBy(i => i.RequestTime)
                .ToList(); // ToList() is needed, otherwise a mistical StackOverflow occurs within IIS.
            // Use the first Exercise as a single instance. Make it the common parent of all Reviews.
            var exercise = exercises.First();
            exercise.Reviews = reviews;

            ViewBag.ExerciseParam = exercise;
            ViewBag.cardIdParam = exercise.CardId.GetValueOrDefault();
            if (exercise.CardId.HasValue)
            {
                ViewBag.cardParam = await ExerciseUtils.GetCardWithItems(exercise.CardId.Value);
            }

            switch (exercise.ArtifactType)
            {
                case ArtifactType.Jpeg:
                    return View("ViewPhoto");
                case ArtifactType.Mp3:
                    return View("ViewRecording");
                default:
                    return HttpNotFound(exercise.ArtifactType);
            }
        }

        // GET: /exercises/upload?dir=BASE64_ENCODED_STRING
        public ActionResult Upload(string dir = "")
        {
            byte[] encodedDataAsBytes = System.Convert.FromBase64String(dir);
            string userDir = System.Text.Encoding.Unicode.GetString(encodedDataAsBytes);
            ViewBag.UserDir = userDir;
            return View();
        }

        // The action name corresponds to the path in audior_settings.xml.
        // Audior hardcodes the path prefix, so routing has limited options.
        // POST: /exercises/save-audior-recording
        [HttpPost]
        public async Task<string> SaveAudiorRecording(string recorderId, string recordName, double duration)
        {
            bool success = false;
            try
            {
                var userId = this.GetUserId();
                // recorderId comes from Audior, 13 digits, milliseconds, current Date in the browser. It is part of Artifact and will be used to update Title with the real title after upload is done.
                var blobName = UploadUtils.ConstractArtifactBlobName(userId, recorderId, recordName);

                using (var stream = Request.InputStream)
                {
                    await AzureStorageUtils.UploadBlobAsync(stream, AzureStorageUtils.ContainerNames.Artifacts, blobName, MediaType.Mp3);
                }

                var length = UploadUtils.DurationToLength(duration);
                await ExerciseUtils.CreateExercise(blobName, userId, ServiceType.IeltsSpeaking, ArtifactType.Mp3, length, null);
                success = true;
            }
            catch (Exception ex)
            {
                return "save=failed\n" + ex.Message;
            }
            // Audior expects only "save=..." in response.
            return "save=" + (success ? "ok" : "failed");
        }

        // TODO obsolete
        // POST: /exercises/save-recording-mobile
        [HttpPost]
        public async Task<ActionResult> SaveRecordingMobile(HttpPostedFileBase fileInput, string recorderId, string recordingTitle)
        {
            /*
             * 1. Save the original media file to a blob
             * 2. Call the remote Transcoding service. Pass the blob name.
             * 3. The Transcoding service saves the MP3 file to a blob and returns its name and the recording's duration.
             * 4. Create a database record.             
             */
            if (fileInput == null)
            {
                return RedirectToAction("RecordSpeech", new { error = "no_file" });
            }

            //  return RedirectToAction("RecordSpeech", new { error = "test01" });

            var contentType = fileInput.ContentType;
            var acceptedContentType = (new[] { MediaType.Amr, MediaType.Gpp, MediaType.QuickTime }).Contains(contentType);
            if (!acceptedContentType)
            {
                return RedirectToAction("RecordSpeech", new { error = contentType });
            }

            var userId = this.GetUserId();

            // 1. Save the original file.
            // The directory structure in Blob Storage is userIdKey/timeKey/originalFileName.ext
            var timeKey = KeyUtils.GetTimeAsBase32();
            var fileName = fileInput.FileName;
            // Sanitize the fileName. Reserved URL characters must be properly escaped.
            fileName = String.IsNullOrWhiteSpace(fileName)
                ? timeKey
                : Uri.EscapeUriString(fileName.Trim());
            var invalidChars = Path.GetInvalidFileNameChars();
            fileName = new String(fileName.Select(i => invalidChars.Contains(i) ? '_' : i).ToArray());
            if (!Path.HasExtension(fileName))
            {
                Path.ChangeExtension(fileName, MediaType.GetExtension(contentType));
            }

            var blobName = KeyUtils.IntToKey(userId) + AzureStorageUtils.DefaultDirectoryDelimiter + timeKey + AzureStorageUtils.DefaultDirectoryDelimiter + fileName;
            using (var stream = fileInput.InputStream)
            {
                await AzureStorageUtils.UploadBlobAsync(stream, AzureStorageUtils.ContainerNames.Recordings, blobName, contentType);
            }

            // 2. Call the transcoding service.
            var host = ConfigurationManager.AppSettings["RecorderHost"];
            var url = String.Format("http://{0}/api/recordings/transcoded/?inputBlobName={1}", host, blobName);
            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(url);
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("RecordSpeech", new { error = "transcoding_error" });
            }
            // 3. Get the results from the service.
            // Error is returned as HTML. Then we get error here: No MediaTypeFormatter is available to read an object of type 'JObject' from content with media type 'text/html'.
            var value = await response.Content.ReadAsAsync<JObject>();
            var outputBlobName = (string)value["outputBlobName"];
            var duration = Convert.ToDecimal((int)value["durationMsec"] / 1000.0m);
            // The transcoder may return -1 if it has failed to parse the ffmpeg logs.
            if (duration < 0)
            {
                // Read the blob and try to determine the duration directly.
                duration = await RecordingUtils.GetMp3Duration(AzureStorageUtils.ContainerNames.Recordings, outputBlobName);
            }
            // 4. Create a database record.
            var exerciseId = await ExerciseUtils.CreateExercise(outputBlobName, userId, ServiceType.IeltsSpeaking, ArtifactType.Mp3,
                duration, recordingTitle);
            // 5. Redirect to the exercise page.
            return RedirectToAction("View", new { Id = exerciseId });
        }

        // POST: /exercises/upload
        [HttpPost]
        public async Task<ActionResult> Upload(HttpPostedFileBase mp3File, HttpPostedFileBase xmlFile,
            string userdir = "", string title = null, string learnerSkype = null)
        {
            int exerciseId = 0;
            int newUserId = 0;

            var userId = this.GetUserId();

            // Save the recording
            if (mp3File != null)
            {
                ViewBag.mp3FileName = mp3File.FileName;
                // We can receive garbage from the wild web.
                try
                {
                    using (var stream = mp3File.InputStream)
                    {
                        var duration = RecordingUtils.GetMp3Duration(stream);
                        if (duration > 0)
                        {
                            var recordingTitle = !String.IsNullOrEmpty(title)
                                ? title
                                : Path.GetFileNameWithoutExtension(mp3File.FileName);

                            exerciseId = await ExerciseUtils.SaveRecording(
                                stream,
                                userId,
                                ArtifactType.Mp3,
                                ServiceType.IeltsSpeaking,

Website/Views/Exercises/Index.cshtml
@{
    ViewBag.NavItem = "IeltsExercises";
}
<style>
    .table > tbody > tr.app-row-review > td {
        border-top-color: transparent;
    }
</style>

<div ng-app="myApp" ng-cloak>
    <div ng-controller="Index">
        <div class="row">
            <div class="col-md-8">
                <h3 class="page-header app">Exercises <small>{{secondaryTitle}}</small></h3>
            </div>
            <div class="col-md-4 app-margin-bottom">
                <ul class="nav nav-pills app-nav-pills">
                    <li data-ui-sref-active="active">
                        <a href="" data-ui-sref="@ArtifactType.Mp3"><i class="fa fa-comment-o fa-fw app-appyellow"></i>&nbsp;Speaking</a>
                    </li>
                    <li data-ui-sref-active="active">
                        <a href="" data-ui-sref="@ArtifactType.Jpeg"><i class="fa fa-pencil fa-fw app-appyellow"></i>&nbsp;Writing</a>
                    </li>
                </ul>
            </div>
        </div>
        <h4 class="text-center app-margin-top-none app-margin-bottom-none">
            <span ng-show="vm.isStateSpeaking()">
                <span class="text-nowrap"><i class="fa fa-microphone fa-fw app-appblue"></i>&nbsp;@Html.ActionLink("Record speech", "RecordSpeech", "Exercises")</span>
                @*<span class="text-nowrap"><i class="fa fa-skype fa-fw app-margin-left"></i>&nbsp;@Html.ActionLink("Record Skype conversation", "Index", "RecorderForSkype")</span>*@
            </span>
            <span ng-show="vm.isStateWriting()">
                <span class="text-nowrap"><i class="fa fa-camera fa-fw app-margin-left app-appblue"></i>&nbsp;@Html.ActionLink("Photograph text", "PhotographWriting", "Exercises")</span>
            </span>
        </h4>
        <hr />
        <div class="row">
            <div class="col-lg-offset-1 col-lg-10">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th class="app-text-right">Length</th>
                            <th>Created</th>
                            <th>Review</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-class="{'app-last-row':$last}" ng-repeat="e in vm.exercises">
                            <td>
                                <a ng-href="{{vm.getViewUrl(e)}}">{{e.title}}</a>
                            </td>
                            <td class="app-text-right">
                                {{e.length | appLength : e.type}}
                            </td>
                            <td>
                                {{e.creationTime | appDateHuman}}
                            </td>
                            <td>
                                <ul class="app-margin-bottom-none">
                                    <li class="app-row-review" ng-repeat="r in e.reviews">
                                        <span ng-class="vm.getReviewStatusStyle(r)"><strong>{{vm.getReviewStatusText(r)}}</strong></span>
                                        &nbsp;{{vm.getReviewStatusTime(r) | appDate}}
                                    </li>
                                </ul>
                                <button class="btn btn-xs" ng-class="(e.reviews.length > 0)?'btn-default':'btn-primary'" ng-click="vm.showCreateRequestModal(e)">Request&nbsp;review</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-muted text-center" style="margin-top:19px;" ng-show="vm.isEmpty()" ng-cloak>
                    You have not done any exercises yet.
                </p>
                <div class="pagination-sm" data-pagination data-total-items="vm.pgTotal" data-items-per-page="vm.pgLimit" data-max-size="5" data-boundary-links="true" data-rotate="false"
                     ng-show="vm.pgTotal>vm.pgLimit" ng-model="vm.pgCurrent" ng-change="vm.pgLoad()"></div>
            </div>
        </div>

    </div><!-- /ng-controller="Ctrl" -->
    <!-- Modals -->
    <!-- cancelRequestModal -->
    <script type="text/ng-template" id="cancelRequestModal">
        <div class="modal-header">
            <h3>Cancel review request</h3>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-offset-1 col-md-10">
                    <p>
                        Review request created on <strong>{{vm.modalParams.review.requestTime | appDate }}</strong>
                        for exercise &quot;<strong>{{vm.modalParams.exercise.title}}</strong>&quot; will be canceled.
                    </p>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary app-btn-disablable" ng-click="vm.ok()" ng-disabled="vm.busy">OK</button>
            <a href="" class="app-close" ng-click="vm.cancel()">Close</a>
        </div>
    </script>
    <!-- /cancelRequestModal -->
    <!-- /Modals -->
</div><!-- /ng-app="myApp" -->
@*@using (Html.BeginInstructionsContainer())
    {
        <ul>
            <li>Press the <em>Record a monologue</em> button to record a speech.</li>
            <li>You can click an exercise title to edit its title, listen to it and view remarks when reviews are ready.</li>
            <li>If an exercise has not been offered for reviewing, you can delete it by pressing the <em>Delete</em> button in the exercise row. </li>
            <li>To offer an exercise for reviewing, press the <em>Offer for reviewing</em> button in the exercise row. </li>
            <li>The list is refreshed every 2 minutes.</li>
        </ul>
    }*@
@section BottomScripts {
    @Scripts.Render(
"~/bundles/angular",
"~/bundles/angular-libs",
"~/bundles/ext-libs",
"~/bundles/app-utils",
"~/app/exercises/utils.js",
"~/app/exercises/index.js"
)}

Website/Views/Exercises/Upload.cshtml
@{
    ViewBag.Title = "Upload exercise recording";
    var pageViewModel = new Runnymede.Website.Models.PageViewModel(this);
}
@if (!String.IsNullOrEmpty(ViewBag.UserDir))
{
    <p class="text-center">
        You can find your most recent recording in the following folder on your computer:
        <br />
        <em>@ViewBag.UserDir</em>
        <br />&nbsp;
    </p>
}
@if (ViewBag.mp3FileName != null)
{
    <div class="col-sm-offset-1 col-sm-10">
        @if (ViewBag.Success)
        {
            <p class="text-success">
                You have successfully uploaded file @ViewBag.mp3FileName. You can go now to the <a href="/exercises">Exercises</a> page to see it.
            </p>
        }
        else
        {
            <p class="text-danger">
                Unable to upload file @ViewBag.mp3FileName. Make sure it is a valid MP3 file.
            </p>
        }
    </div>
}
    @* ExercisesController.MaxTitleLength = 70 *@
    @using (Html.BeginForm(null, null, null, FormMethod.Post, new { @class = "col-sm-offset-1 col-sm-10 form-horizontal", @enctype = "multipart/form-data" }))
    {
        @Html.Hidden("userdir", (string)ViewBag.UserDir)
        <div>
            <input type="file" name="mp3File" class="btn btn-default" accept="audio/mpeg" required />
        </div>
        if (pageViewModel.IsTeacher)
        {
            <div>
                <input type="file" name="xmlFile" class="btn btn-default" accept="text/xml" />
            </div>
            <div>
                <input type="text" name="learnerSkype" class="form-control col-sm-10" maxlength="100" placeholder="Write the Skype name of the learner." />
            </div>
        }
        <br />
        <div>
            <input type="text" name="title" class="form-control col-sm-10" maxlength="70" placeholder="Write the exercise title here (maximum 70 chars.)" />
        </div>
        <br />
        <br />
        <div>
            <input type="submit" class="btn btn-primary" value="Upload &raquo;" />
            <input type="reset" value="Reset" class="btn btn-default btn-sm col-sm-offset-1">
        </div>
    }

Website/Views/Exercises/ViewPhoto.cshtml
@{
    ViewBag.NavItem = "IeltsExercises";
    ViewBag.Title = ServiceType.GetTitle(ViewBag.ExerciseParam.ServiceType);
    ViewBag.SecondaryTitle = "View exercise";
}
@section HeadScripts {
    @Styles.Render(
"~/bundles/animate-css",
"~/bower_installer/ng-tags-input/ng-tags-input.min.css",
"~/bower_installer/ng-tags-input/ng-tags-input.bootstrap.min.css"
)
}
@* Do not hide the video player! See the comments in the partial. *@
<div ng-app="myApp" ng-controller="ViewPhoto">

    @Html.Partial("_TitlePartial")

    <hr />

    @Html.Partial("_CanvasPartial")

    @Html.Partial("_BottomPartial")

</div> <!-- /ng-app -->
@section BottomScripts {
    <script>
        app.exerciseParam = @JavaScriptConvert.Serialize(ViewBag.ExerciseParam);
        app.cardParam = @JavaScriptConvert.Serialize(ViewBag.cardParam);
        app.hostPageParam = 'HostPage_ViewWriting';
    </script>
    @Scripts.Render(
"~/bundles/angular",
"~/bundles/angular-libs",
"~/bundles/ext-libs",
"~/bundles/app-utils",
"~/bower_installer/ng-tags-input/ng-tags-input.min.js",
"~/bower_installer/signalr/jquery.signalR.min.js",
"~/app/shared/utils-youtube.js",
"~/app/shared/library-data.js",
"~/app/shared/library.js",
"~/app/shared/exercises.js",
"~/app/shared/exercises-writing.js",
"~/app/exercisesIelts/utils-data.js",
"~/app/exercises/utils.js",
"~/app/exercises/utils-viewCtrlBase.js",
"~/app/exercises/viewPhoto.js"
)
}

Website/Views/Exercises/ViewRecording.cshtml
@{
    ViewBag.Title = "Recording";
}
@section HeadScripts {
    @Styles.Render(
"~/bundles/animate-css",
"~/bower_installer/ng-tags-input/ng-tags-input.min.css",
"~/bower_installer/ng-tags-input/ng-tags-input.bootstrap.min.css"
)
}
@* Do not hide the video player! See the comments in the partial. *@
<div ng-app="myApp">

    @Html.Partial("_SplashPartial")

    <div ng-controller="ViewRecording" ng-cloak>

        @Html.Partial("_TitlePartial")

        <div ng-controller="AudioPlayer">
            <div class="text-center app-margin-top app-margin-bottom" ng-show="!vma.player">
                <i class="fa fa-spinner fa-spin fa-fw fa-2x"></i>&nbsp;&nbsp;Loading&nbsp;...
            </div>

            <div ng-show="vma.player">

                @Html.Partial("_AudioPlayerControlsPartial")

            </div>

            <div class="panel panel-default app-margin-top">
                <div class="panel-heading">
                    <h4 class="panel-title">Remarks</h4>
                </div>
                <div class="panel-body" style="padding:0">

                    <table class="table table-condensed table-hover app-margin-bottom-none">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Spot</th>
                                <th>Correction</th>
                                <th>Comment</th>
                                <th ng-if="vm.manyReviews()">Reviewer</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="r in vm.$appRemarks.remarks" ng-click="vma.selectRemark(r)">
                                <td>
                                    <button class="btn btn-default btn-xs" ng-show="vma.isSelected(r)" ng-click="vma.playRemarkSpot(r)" title="Replay"><i class="fa fa-repeat"></i></button>
                                </td>
                                <td class="text-nowrap">
                                    from&nbsp;{{r.start | appSecToMinSec}}
                                    to&nbsp;{{r.finish | appSecToMinSec}}
                                </td>
                                <td>
                                    {{r.correction}}
                                </td>
                                <td>
                                    {{r.comment}}
                                </td>
                                <td ng-if="vm.manyReviews()">
                                    {{vm.getReviewerName(r)}}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- /ng-controller="AudioPlayer" -->

        @Html.Partial("_BottomPartial")

    </div> <!-- /ng-controller="Viewer" -->
</div> <!-- /ng-app -->
@*@using (Html.BeginInstructionsContainer())
    {
        <ul>
            <li>You can edit the title of the exercise.</li>
            <li>You can listen to the record.</li>
            <li>If a review for the exercise is available, you can see remarks made by the reviewer.</li>
            <li>You can listen to the same remark spot many times by clicking the button with the circular arrow</li>
            <li>There may be a tag for a remark. By clicking on it you will be redirected to an external website which may help you to understand the remark.</li>
        </ul>
    }*@
@section BottomScripts {
    <script>
        app.exerciseParam = @JavaScriptConvert.Serialize(ViewBag.ExerciseParam);
        app.cardIdParam = @JavaScriptConvert.Serialize(ViewBag.cardIdParam);
        app.cardParam = @JavaScriptConvert.Serialize(ViewBag.cardParam);
        app.hostPageParam = 'HostPage_ViewRecording';
    </script>
    @Scripts.Render(
"~/bundles/angular",
"~/bundles/angular-libs",
"~/bundles/ext-libs",
"~/bundles/app-utils",
//<script src="+//ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-touch.min.js"></script>
"~/bower_installer/angular-touch/angular-touch.min.js",
"~/bower_installer/venturocket-angular-slider/angular-slider.min.js",
"~/bower_installer/ng-tags-input/ng-tags-input.min.js", // TODO obsolete??
                                                        //"~/bower_installer/signalr/jquery.signalR.min.js",
"~/app/shared/utils-youtube.js",
"~/app/shared/library-data.js",
"~/app/shared/library.js", // TODO ??

"~/app/exercises/utils.js",
"~/app/exercises/utils-card.js",
"~/app/shared/utils-player.js",
"~/app/shared/exercises.js",
"~/app/shared/exercises-recording.js",
"~/app/exercisesIelts/utils-data.js",
"~/app/exercises/utils-viewCtrlBase.js"
, "~/app/exercises/viewRecording.js"
)
}

Website/Views/Exercises/ViewRecording0.cshtml
@{
    ViewBag.Title = "Recording";
}
@section HeadScripts {
    @* SoundManager must be loaded as early as possible. Otherwise browser security may block Flash <-> JS communication after certain JQuery DOM manipulations by a third-party code. *@
    @Scripts.Render("~/bundles/soundmanager2")
    @Styles.Render(
"~/bundles/animate-css",
"~/bower_installer/ng-tags-input/ng-tags-input.min.css",
"~/bower_installer/ng-tags-input/ng-tags-input.bootstrap.min.css"
)
}
@* Do not hide the video player! See the comments in the partial. *@
<div ng-app="myApp" ng-controller="ViewRecording">

    @Html.Partial("_TitlePartial")
    <div ng-controller="AudioPlayer" ng-cloak>
        <hr />
        <div class="text-center" ng-show="vma.autoLoad && !vma.soundLoaded">
            <i class="fa fa-spinner fa-spin fa-fw fa-2x"></i>&nbsp;&nbsp;Loading recording...
            <hr />
        </div>
        <div class="app-margin-bottom" ng-show="!vma.autoLoad || vma.soundLoaded">
            @Html.Partial("_AudioPlayerControlsPartial")
        </div>
        <div id="soundmanager-debug"></div>

        <div class="panel panel-default" ng-cloak>
            <div class="panel-heading">
                <h4 class="panel-title">Remarks</h4>
            </div>
            <div class="panel-body" style="padding:0">

                <table class="table table-condensed table-hover app-margin-bottom-none">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Spot</th>
                            <th>Correction</th>
                            <th>Comment</th>
                            <th ng-if="vm.manyReviews()">Reviewer</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="r in vm.$appRemarks.remarks" ng-click="vma.selectRemark(r)">
                            <td>
                                <button class="btn btn-default btn-xs" ng-show="vma.isSelected(r)" ng-click="vma.playRemarkSpot(r)" title="Replay"><i class="fa fa-repeat"></i></button>
                            </td>
                            <td class="text-nowrap">
                                from&nbsp;{{r.start | appMsecToMinSec}}
                                to&nbsp;{{r.finish | appMsecToMinSec}}
                            </td>
                            <td>
                                {{r.correction}}
                            </td>
                            <td>
                                {{r.comment}}
                            </td>
                            <td ng-if="vm.manyReviews()">
                                {{vm.getReviewerName(r)}}
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

    </div><!-- /ng-controller="AudioPlayer" -->

    @Html.Partial("_BottomPartial")

</div><!-- /ng-controller="Viewer" -->
@*@using (Html.BeginInstructionsContainer())
    {
        <ul>
            <li>You can edit the title of the exercise.</li>
            <li>You can listen to the record.</li>
            <li>If a review for the exercise is available, you can see remarks made by the reviewer.</li>
            <li>You can listen to the same remark spot many times by clicking the button with the circular arrow</li>
            <li>There may be a tag for a remark. By clicking on it you will be redirected to an external website which may help you to understand the remark.</li>
        </ul>
    }*@
@section BottomScripts {
    <script>
        app.exerciseParam = @JavaScriptConvert.Serialize(ViewBag.ExerciseParam);
        app.cardParam = @JavaScriptConvert.Serialize(ViewBag.cardParam);
        app.hostPageParam = 'HostPage_ViewRecording';
    </script>
    @Scripts.Render(
"~/bundles/angular",
"~/bundles/angular-libs",
"~/bundles/ext-libs",
"~/bundles/app-utils",
            //<script src="+//ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular-touch.min.js"></script>
"~/bower_installer/angular-touch/angular-touch.min.js",
"~/bower_installer/venturocket-angular-slider/angular-slider.min.js",
"~/bower_installer/ng-tags-input/ng-tags-input.min.js",
"~/bower_installer/signalr/jquery.signalR.min.js",
"~/app/shared/utils-youtube.js",
"~/app/shared/library-data.js",
"~/app/shared/library.js",
"~/app/shared/exercises.js",
"~/app/shared/exercises-recording.js",
"~/app/exercisesIelts/utils-data.js",
"~/app/exercises/utils.js",
"~/app/exercises/utils-viewCtrlBase.js",
"~/app/exercises/viewRecording.js"
)
}