Website/Controllers/Mvc/IeltsController.cs
using System.Web.Mvc;

namespace Runnymede.Website.Controllers.Mvc
{
    // We use this path in URLs pointing to landing pages in AdWords

    public class IeltsController : Controller
    {
        public ActionResult Index()
        {
            //return RedirectToAction("Index", "Home"); // returns 302 Moved
            return View("../Home/Index");
        }

        public ActionResult Info()
        {
            return View("../Home/Index");
        }

        public ActionResult Speaking()
        {
            return View("../Home/Index");
        }

        public ActionResult Writing()
        {
            return View("../Home/Index");
        }

    }
}

Website/Controllers/Mvc/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Runnymede.Website.Controllers.Mvc
{
    public class InfoController : Runnymede.Website.Utils.CustomController
    {
        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult TermsOfService()
        {
            return View();
        }

        public ActionResult PrivacyPolicy()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        [RequireHttps]
        public ActionResult Dignicom()
        {
            return View();
        }

        public ActionResult HowItWorks()
        {
            return View();
        }

        public ActionResult SupportedBrowsers()
        {
            return View();
        }

        public ActionResult UnsupportedBrowser()
        {
            return View();
        }

        public ActionResult Ielts()
        {
            return View();
        }

    }
}

Website/Views/Shared/_ApplicationInsightsPartial.cshtml
<script type="text/javascript">
    var appInsights=window.appInsights||function(config){
        function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
    }({
        instrumentationKey:"57cd18b2-07d0-4d26-9354-da492689cbc9"
    });

    window.appInsights=appInsights;
    appInsights.trackPageView();
</script>

Website/Views/Shared/_AudioPlayerControlsPartial.cshtml
<style>
    /* #region ----------- Slider */

    .my-slider-container {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        /*-khtml-user-select: none;*/
        -moz-user-select: -moz-none;
        -ms-user-select: none;
        user-select: none;
    }

    slider {
        display: block;
        position: relative;
        height: 16px;
        width: 100%;
    }

        slider span.bar {
            height: 100%;
            background: #dddddd;
            left: 0;
            z-index: 0;
        }

        slider span.pointer {
            width: 16px;
            top: 0;
            bottom: 0;
            background-color: #007ebd; /* #006394 appBlue */
            border-radius: 4px;
            border: 1px solid #006da3;
        }

        slider span.bubble {
            font-family: Menlo, Monaco, Consolas, "Courier New", monospace; /* Bootstrap's font-family-monospace */
            font-size: 13px;
            top: -16px;
            text-align: center;
            text-shadow: none;
        }

            slider span.bubble.limit {
                top: -2px;
            }

    /* The slider directive uses the new HTML5 input[type=range] tag in modern browsers (IE10+). It is the top-most element, so it reacts to the user actions. But its opacity is set to 0, so it is invisible. */
    input[type=range] {
        cursor: pointer;
    }

        input[type=range]::-ms-tooltip {
            display: none;
        }

    /* #endregion ----------- /Slider */

    /* #region ----------- Review editor/viewer */

    div.my-spot-mark-container {
        width: 100%;
        height: 16px;
        position: relative;
    }

    a.my-spot-mark {
        background-color: #006394; /* appBlue link-color */
        position: absolute;
        padding: 0px;
        width: 4px;
        height: 100%;
        z-index: 10;
    }

        a.my-spot-mark:hover {
            background-color: #007ebd; /* appBlue lighten(link-color, 8%) */
        }

        a.my-spot-mark.active {
            background-color: #ac1f28; /* appRed */
            top: -16px;
        }

    .my-item {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    /* #endregion ----------- /Review editor/viewer */
</style>

<div class="app-margin-top app-margin-bottom my-item">Question: {{vma.cardItem.content}}</div>
<div class="row">
    <div class="col-md-12">
        <div style="margin: 0px 0px 10px;">
            <div class="my-slider-container">
                <slider floor="0" ceiling="{{vma.exercise.length}}" ng-model="vma.sliderPosition" ng-change="vma.onSliderChange()" translate-fn="vma.positionFormatting"></slider>
            </div>
            <div class="my-spot-mark-container">
                <a class="my-spot-mark" href="javascript:;" ng-repeat="r in vm.$appRemarks.remarks"
                   ng-click="vma.selectRemark(r)" ng-class="{active: vma.isSelected(r)}" ng-style="{ left: vma.getSpotMarkPosition(r) + '%' }"></a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-offset-1 col-sm-2">
        <button class="btn btn-default btn-block" ng-click="vma.rewind()" ng-disabled="vma.player.currentTime == 0"><i class="fa fa-step-backward fa-fw"></i>&nbsp;Rewind</button>
    </div>
    @* The &nbsp; separates buttons when the layout jumps on col-sm  *@
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-4">
        <button id="playButton" type="button" class="btn btn-default btn-block" ng-class="{active: vma.player.isPlaying()}" ng-click="vma.turnPlayer()">
            <i class="fa fa-fw" ng-class="vma.player.isPlaying() ? 'fa-pause' : 'fa-play'"></i>&nbsp;<span ng-bind="vma.player.isPlaying() ? 'Pause' : 'Play'"></span>
        </button>
    </div>
    @*<div class="col-sm-4"></div>*@
</div>

Website/Views/Shared/_CanvasPartial.cshtml
<style>
    #myCanvas {
        /*height: auto; If this rule is present, height is wrong in IE10. */
        border: none; /* If border, see +http://stackoverflow.com/a/27204937/2808337 */
        z-index: 1;
    }

    #myPanel {
        position: fixed;
        top: 40%;
        display: block;
        right: 0px;
        min-width: 355px;
        z-index: 2;
        background-color: rgba(222,222,222,0.1);
        border-color: transparent;
    }

        #myPanel p {
            max-width: 400px;
            background-color: white;
            padding: 5px;
            border-radius: 3px;
        }

    .my-translucent {
        background-color: rgba(255,255,255,0.9);
        border-radius: 3px;
    }

    #myDeleteBtn:hover, #myDeleteBtn:focus, #myDeleteBtn:active {
        background-color: #e6e6e6;
    }

    .radio-inline input[type="radio"] {
        margin-left: -14px;
    }

    .my-margin-top {
        margin-top: 15px;
    }
</style>

@*<div class="row app-margin-top" ng-show="vm.canEditLength()" ng-cloak>
        <div class="col-sm-4 col-md-3">
            <div class="input-group">
                <span class="input-group-addon"><strong>Word count</strong></span>
                <input type="text" class="form-control" ng-model="vm.exercise.length" maxlength="4">
                <span ng-class="vm.isLengthDirty() ? 'input-group-btn' : 'input-group-addon'">
                    <button type="button" class="btn btn-default" ng-show="vm.isLengthDirty()" ng-click="vm.saveLength()">
                        <i class="fa fa-check fa-fw text-success animated flash infinite"></i><span>Save</span>
                    </button>
                </span>
            </div><!-- /input-group -->
        </div>
    </div>*@

<div ng-controller="Canvas" ng-cloak>
    <div class="row">
        <div class="col-lg-12">
            <div class="row app-margin-bottom">
                <div class="col-xs-3">
                    <span style="position:relative;top:5px;" ng-show="!vm.canEditLength()">Word count: <strong>{{vma.exercise.length}}</strong></span>
                </div>
                <div class="col-xs-4" style="height:30px;">
                    <div ng-show="vma.images.length > 1">
                        <strong style="position:relative;top:-10px;">Page</strong>
                        <div class="pagination-sm app-margin-top-none app-margin-bottom-none app-margin-left-half" data-pagination data-total-items="vma.images.length" data-items-per-page="1" direction-links="false" data-boundary-links="false" data-rotate="false" ng-model="vma.page" ng-change="vma.clear()"></div>
                    </div>
                </div>
                <div class="col-xs-5">
                    <button class="btn btn-default btn-sm app-btn-disablable" ng-click="vma.zoomIn()" ng-disabled="vma.scaleIndex == vma.scales.length-1"><i class="fa fa-search-plus fa-fw"></i>&nbsp;Zoom&nbsp;in</button>
                    <button class="btn btn-default btn-sm app-btn-disablable" ng-click="vma.zoomOut()" ng-disabled="vma.scaleIndex == 0"><i class="fa fa-search-minus fa-fw"></i>&nbsp;Zoom&nbsp;out</button>
                </div>
            </div>

            <div style="margin-bottom:14px;">
                <canvas id="myCanvas"></canvas>
            </div>

            <div id="myPanel" class="panel panel-default" ng-show="vma.remark" ng-cloak>
                <div class="panel-body">
                    <div>
                        <div class="text-right">
                            <strong class="my-translucent">&nbsp;Correction&nbsp;</strong>
                        </div>
                        <textarea class="form-control app-textarea" rows="3" cols="40" ng-show="vma.isEditing(vma.remark)" ng-model="vma.remark.correction" ng-change="vm.makeDirty(vma.remark)"></textarea>
                        <p ng-show="!vma.isEditing(vma.remark)">{{vma.remark.correction}}</p>
                    </div>
                    <div class="my-margin-top">
                        <div class="text-right">
                            <strong class="my-translucent">&nbsp;Comment&nbsp;</strong>
                        </div>
                        <textarea class="form-control app-textarea" rows="3" cols="40" ng-show="vma.isEditing(vma.remark)" ng-model="vma.remark.comment" ng-change="vm.makeDirty(vma.remark)"></textarea>
                        <p class="app-margin-bottom-none" ng-show="!vma.isEditing(vma.remark)">{{vma.remark.comment}}</p>
                    </div>
                    <div class="my-margin-top" ng-show="vma.isEditing(vma.remark)">
                        <span class="my-translucent" style="padding-bottom:3px;">
                            <label class="radio-inline">
                                <input type="radio" ng-value="false" ng-model="vma.remark.like" ng-change="vm.makeDirty(vma.remark);vma.repaint()" />
                                <i class="fa fa-thumbs-down fa-fw text-danger"></i>
                                <strong>Dislike</strong>
                            </label>
                            <label class="radio-inline">
                                <input type="radio" ng-value="true" ng-model="vma.remark.like" ng-change="vm.makeDirty(vma.remark);vma.repaint()" />
                                <i class="fa fa-thumbs-up fa-fw text-success"></i>
                                <strong>Like&nbsp;</strong>
                            </label>
                        </span>
                        <button class="btn btn-default btn-xs app-margin-left my-translucent" title="Delete the remark" ng-click="vm.showDeleteRemarkModal(vma.remark)"><i class="fa fa-times fa-fw text-danger"></i>Delete</button>
                        <span class="pull-right app-1px-down my-translucent">&nbsp;<a href="" ng-click="vma.selectRemark(null)" title="Close the panel"><strong>Close</strong></a>&nbsp;</span>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Website/Views/Shared/_EnglishOnlyNote.cshtml
<!--Deutsch--><div class="english-only-note lg-de-de">Dieser Inhalt ist derzeit nur in englischer Sprache verfügbar. Wir entschuldigen uns für die Unannehmlichkeiten.</div>
<!--Français--><div class="english-only-note lg-fr-fr">Ce contenu est disponible en anglais uniquement à l'heure actuelle. Veuillez nous excuser pour ce désagrément.</div>
<!--Italiano--><div class="english-only-note lg-it-it">Il contenuto è attualmente disponibile solo in inglese. Ci scusiamo per l'inconveniente.</div>
<!--Español--><div class="english-only-note lg-es-es">Este contenido solo está disponible en inglés. Sentimos los inconvenientes.</div>
<!--Português--><div class="english-only-note lg-pt-br">No momento, o conteúdo está disponível apenas em inglês. Pedimos desculpas pela inconveniência.</div>
<!--русский--><div class="english-only-note lg-ru-ru">Это содержимое в данный момент доступно только на английском языке. Приносим извинения за неудобство.</div>
<!--日本語--><div class="english-only-note lg-ja-jp">このコンテンツは現在英語でのみ提供されています。ご不便をおかけして申し訳ありません。</div>
<!--한국어--><div class="english-only-note lg-ko-kr">이 콘텐츠는 현재 영어로만 제공됩니다. 불편을 드려 죄송합니다.</div>
<!--中文(简体)--><div class="english-only-note lg-zh-cn">当前仅提供了此内容的英文版本。对此给您带来的不便，我们深表歉意。</div>
<!--中文(繁體)--><div class="english-only-note lg-zh-tw">此內容目前僅提供英文。很抱歉造成您的不便。</div>

Website/Views/Shared/_FooterPartial.cshtml
<div class="row">
    <div class="col-sm-offset-2 col-sm-7">
        <table>
            <tr>
                <td>
                    <p class="small text-muted"><strong>LEARN</strong></p>
                    @*<p>@Html.ActionLink("How it works", "HowItWorks", "Info")</p>*@
                    @*<p>@Html.ActionLink("IELTS", "Ielts", "Info")</p>*@
                    <p>@Html.ActionLink("Prices", "BuyServices", "Account")</p>
                </td>
                @*<td>
                        <p class="small text-muted"><strong>TEACHERS</strong></p>
                        <p>@Html.ActionLink("How it works", "HowItWorks", "Info")</p>
                        <p><a href="http://support.englisharium.com/support/solutions/5000109955">FAQ</a></p>
                    </td>*@
                <td>
                    <p class="small text-muted"><strong>SUPPORT</strong></p>
                    <p class="hidden-xs">Email: <img src="~/content/images/email-support.png" width="160" height="15" /></p>
                    <p class="visible-xs-inline-block"><a href="http://support.englisharium.com/support/tickets/new">Contact Us</a></p>
                    <p><a href="http://englisharium.freshdesk.com/support/solutions/5000105857">Frequently Asked Questions</a></p>
                </td>
                <td>
                    <p class="small text-muted"><strong>POLICIES</strong></p>
                    <p>@Html.ActionLink("Terms of Service", "TermsOfService", "Info")</p>
                    <p>@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Info")</p>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-sm-3 app-margin-bottom">
        <span class="text-muted app-margin-left">&copy;&nbsp;2015</span>
        @Html.ActionLinkWithProtocol("Dignicom" + ((char)160).ToString() + "Inc.", "Dignicom", "Info", "https", new { @class = "credit" })
    </div>
</div>

Website/Views/Shared/_GoogleAnalyticsPartial.cshtml
@model System.Int32
@* +https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced *@
<script async src='//www.google-analytics.com/analytics.js'></script>
<script>
    window.ga = window.ga || function () { (ga.q = ga.q || []).push(arguments) }; ga.l = +new Date;
    ga('create', 'UA-40125627-3', 'auto');
    @if (Model > 0) {
        @Html.Raw("ga('set', 'userId', '" + @Model.ToString() + "');")
    }
    
    ga('send', 'pageview');
</script>

Website/Views/Shared/_HeaderPartial.cshtml
@model Runnymede.Website.Models.PageViewModel
@functions{
    public string NavClass(string navItem)
    {
        return navItem == ViewBag.NavItem ? "active" : "";
    }
}
@{
//var avatarUrl = AzureStorageUtils.GetBlobUrl(AzureStorageUtils.ContainerNames.AvatarsSmall, KeyUtils.IntToKey(Model.UserId), Request.IsSecureConnection);
}
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            @*<div class="navbar-brand app app-collapsable-brand">*@
            <div class="navbar-brand app">
                @Html.ActionLink("Englisharium", "Index", "Home", null, new { @class = "app-appyellow", @style = "text-decoration:none;" })
            </div>
            @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#headerCollapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
            <button type="button" class="navbar-toggle" style="padding:4px 10px 5px;" data-toggle="collapse" data-target="#headerCollapse">
                <span class="sr-only">Toggle navigation</span>
                <span style="color:white;font-size:15px;">Menu<b class="caret"></b></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="headerCollapse">
            <ul class="nav navbar-nav app">
                @if (!Model.IsTeacher)
                {
                    <li class="@NavClass("IeltsExercises")">@Html.ActionLink("IELTS Exercises", "Index", "ExercisesIelts")</li>
                    <li class="@NavClass("Library")">@Html.ActionLink("Library", "Index", "Library")</li>
                    @*<li class="@NavClass("Sessions")">@Html.ActionLink("Sessions", "Index", "Sessions")</li>*@
                    <li class="@NavClass("Games")">@Html.ActionLink("Game", "LuckyYou", "Games", null, new { tabindex = "-1" })</li>
                }
                @if (Model.IsTeacher)
                {
                    <li class="@NavClass("Reviews")">@Html.ActionLink("Reviews", "Index", "Reviews", null, new { tabindex = "-1" })</li>
                    <li class="@NavClass("Library")">@Html.ActionLink("Library", "Index", "Library")</li>
                }
            </ul>
            <ul class="nav navbar-nav navbar-right app">
                @if (Request.IsAuthenticated)
                {
                    @*<li>
                            @Html.Raw(
                             @Html.ActionLinkWithProtocol("[replacetext]", "Edit", "Account", "https", new { tabindex = "-1", @class = "app-collapsable-avatar", @style = "padding:4px;" })
                            .ToHtmlString()
                             .Replace("[replacetext]", "<img class=\"img-circle\" id=\"navAvatar\" width=\"32\" height=\"32\" src=\"" + @avatarUrl + "\" title=\"" + @Model.DisplayName + "\" />")
                        )
                        </li>*@
                    <li class="dropdown app-dropdown-hover @NavClass("Account")">
                        <a class="dropdown-toggle" href="javascript:;" data-toggle="dropdown">@Model.DisplayName<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLinkWithProtocol("Profile", "Edit", "Account", "https", new { tabindex = "-1" })</li>
                            <li>@Html.ActionLinkWithProtocol("Transactions", "Transactions", "Account", "https", new { tabindex = "-1" })</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLinkWithProtocol("Log out", "Logout", "Account", "http", new { tabindex = "-1" })</li>
                        </ul>
                    </li>
                }
                else
                {
                    <li class="@NavClass("Account")">@Html.ActionLinkWithProtocol("Log in", "Login", "Account", "https", null)</li>
                }
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

Website/Views/Shared/_HelpPartial.cshtml
@* This code snippet is a good candidate to become an Angular directive. *@
@model System.String
<div class="row" ng-controller="Help">
    <div class="col-sm-offset-1 col-md-offset-2" ng-class="vm.isCollapsed ? 'col-sm-3' : 'col-sm-10 col-md-8'">
        <div class="panel panel-default app-margin-bottom-none">
            <div class="panel-heading">
                <i class="fa fa-question-circle fa-fw app-1px-down"></i>
                <a href="" class="app-margin-left-half" ng-click="vm.onClick()">
                    {{vm.isCollapsed ? 'Show help' : 'Hide help'}}
                    <i class="fa fa-fw" ng-class="vm.isCollapsed ? 'fa-chevron-right' : 'fa-chevron-down'"></i>
                </a>
            </div>
            <div class="panel-body" collapse="vm.isCollapsed">
                <div ng-include="vm.include"></div>
            </div>
        </div>
    </div>
</div>
<script>
    var app = app || {};
    app.helpFileParam = '@Model';
</script>

Website/Views/Shared/_Layout.cshtml
@{
    var pageViewModel = new Runnymede.Website.Models.PageViewModel(this);
    var sendAnalytics = !Html.IsDebug() && !(new int[] { 1099489445, 1245020022 }).Contains(pageViewModel.UserId);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Englisharium</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    @*<link href='+http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'> //Roboto bold looks ugly in Chrome. *@
    @Styles.Render("~/bundles/app-css")
    @RenderSection("HeadScripts", required: false)
    @if (sendAnalytics)
    {
        @Html.Partial("_ApplicationInsightsPartial")
        @Html.Partial("_GoogleAnalyticsPartial", pageViewModel.UserId)
    }
</head>
<body>
    <!--[if IE]>
    <script>
        if (!window.document.documentMode || window.document.documentMode < 10) {
            window.location = "/info/unsupported-browser";
        }
    </script>
    <![endif]-->
    @*<!-- The header is not in a container -->*@
    <header>
        @Html.Partial("_HeaderPartial", pageViewModel)
    </header>
    <section class="container">
        @if (ViewBag.Title != null)
        {
            <h3 class="page-header app">
                @ViewBag.Title
                @if (ViewBag.SecondaryTitle != null)
                {
                    <small>@ViewBag.SecondaryTitle</small>
                }
            </h3>
        }
        @RenderBody()
    </section>
    @*<!-- The footer separator is not in a container and goes full page width -->*@
    <hr class="app-appred" />@* appRed *@
    <footer class="container app-footer">
        @Html.Partial("_FooterPartial")
    </footer>
    @* bootstrap.js is needed for the dropdown menu in the top navbar and for scrollspy in the Info controller pages *@
    @Scripts.Render(
"~/bundles/jquery",
"~/bundles/bootstrap"
        )
    <script>
        var app = app || {};
        @if (Request.IsAuthenticated)
        {
            <text>app.selfUserParam = @JavaScriptConvert.Serialize(pageViewModel.SelfUserParam);</text>
        }
    </script>
    @RenderSection("BottomScripts", required: false)
</body>
</html>

Website/Views/Shared/_NotAuthenticatedDivPartial.cshtml
@model System.String
@if (!Request.IsAuthenticated)
{
    <div class="row">
        <div class="@Model">
            <div class="alert alert-warning text-center app-margin-bottom-none" role="alert">
                Please @Html.ActionLinkWithProtocol("log in", "Login", "Account", "https", null, new { returnUrl = Request.Url.PathAndQuery }, null) to enable this feature
            </div>
        </div>
    </div>
}

Website/Views/Shared/_NotAuthenticatedSpanPartial.cshtml
@if (!Request.IsAuthenticated)
{ 
    <span class="alert alert-warning app-warning" role="alert">
        Please @Html.ActionLinkWithProtocol("log in", "Login", "Account", "https", null, new { returnUrl = Request.Url.PathAndQuery }, null) to enable this feature
    </span>
}

Website/Views/Shared/_SplashPartial.cshtml
@* Show the splash screen until Angular is loaded and the .ng-cloak removed. 
    Make shure this partial is placed inside @ng-app but outside of any @ng-cloak *@
<div class="ng-cloak app-splash-backdrop">
    <div class="app-splash">
        <i class="fa fa-spinner fa-spin fa-fw fa-2x app-2px-up"></i>&nbsp;&nbsp;Loading&nbsp;...
    </div>
</div>